Revert "Deleted pszMainKey pszTestKey MainPubKey TestPubKey"
This reverts commit 752c3280f11ae669cf3ebec129b626d6a3b50aa1.

ERROR: CSyncCheckpoint::CheckSignature() : SetPubKey failed